### ISSUE TITLE
Failing with 1.12-dev.5.3: test/parse_test.dart: dot-dot 2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/package_config#29]

**Comment by pq** [comment]
Chatting with @hterkelsen, this looks related to fixes related to https://github.com/dart-lang/sdk/issues/23809. @lrhn : curious what you think?

**Comment by kevmoo** [comment]
We should move quick if we think https://github.com/dart-lang/sdk/issues/23809 should be fixed in 1.12

**Comment by pq** [comment]
Some more context.  Failing test can be viewed in the [travis build](https://travis-ci.org/dart-lang/package_config).

Also, easily reproed locally.  Here's the salient bit of the stack trace:

    00:00 [32m+10[0m[31m -1[0m: parse: dot-dot 2[0m
    Invalid argument (packageUri): Package URIs must not start with a '/': Instance of 'Uri'
    package:package_config/src/util.dart 67:5            checkValidPackageUri
    package:package_config/src/packages_impl.dart 37:26  PackagesBase.resolve
    test/parse_test.dart 80:21                           main.<fn>

**Comment by pq** [comment]
> We should move quick if we think dart-lang/sdk#23809 should be fixed in 1.12

Agreed.  What's not clear to me is whether this is a fix for `packages_impl.dart` or the test. Luckily @lrhn should know a lot better.

**Comment by lrhn** [comment]
It's a bug in the test.
Basically the URI `package:qux/../foo` is normalized to `package:/foo`. This is correct, it's the same result you get if you resolve `../foo` wrt. `package:qux/`. That's just the wonders of URI resolution - a URI with a scheme is absolute anyway, so resolution has no problem adding a leading `/` to the path.

We don't allow `package:/foo` because it starts with a slash (alternatively: has an empty package name).
The change was that the URI got normalized where it used to contain the `..`. It's probably impossible to create a package URI containing `..` now.

**Comment by pq** [comment]
Fixed.
