### ISSUE TITLE
Add logic to produce a package "map"

### ISSUE THREAD

**Issue by sethladd** [dart-lang/package_config#6]
It would be great to use this library to try the various mechanisms to produce a package "mapping":

--package-root
--packages
look next to the entry point for a packages/ dir
look next to entry point for a .packages file
try a parent directory for a .packages file

**Comment by eernstg** [comment]
If it is OK to check the parent directory for a `.packages` file then we
might as well check for `packages` as well.

A concrete example where I've seen the need: When `pub build` creates
`packages` symlinks on the source side (that as, the file tree under
`my_package/web`, or `my_package/X` where X is the final argument to `pub
build ..`), it creates them in all subdirectories. On the target side
(my_package/build/web etc.) there are no symlinks (such that the build file
tree can be copied without breaking), and for space economy only the
topmost 'packages' directory is created. This means that Dart code may run
on the source side and break on the target side, because the former has a
local `packages` directory (link) and the latter doesn't (so the latter
needs a --package-root argument).

In both cases, the question is whether we will (ever? too often?) use an
unintended `.packages` file (or `packages` directory), because there is
none (of the right kind), but somewhere, too far up the path to the root
directory, we find some arbitrary different thing that has the same name.

This can be a security problem, if an attacker gets a chance to create a
rogue `.packages` file in a suitable directory on an important web server,
and the above-mentioned glitch causes a search for `.packages` in superdirs
that skips over the `build/<something>/packages` dir and finds the rogue
file.


On Thu, May 21, 2015 at 1:22 AM, Seth Ladd <notifications@github.com> wrote:

> It would be great to use this library to try the various mechanisms to
> produce a package "mapping":
>
> --package-root
> --packages
> look next to the entry point for a packages/ dir
> look next to entry point for a .packages file
> try a parent directory for a .packages file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/package_config/issues/6>.
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by sethladd** [comment]
Hi @eernstg thanks for the comments! The workflow for finding packages is defined over in https://github.com/lrhn/dep-pkgspec. Please open a new issue there with any comments on the workflow. Thanks!

**Comment by lrhn** [comment]
We *could* try looking for packages directories in the parent path. It might be convenient at times.
One of the reason for why I have chosen not to do that is as a subtle encouragement to switch to a .packages file. 

Eventually pub will stop creating packages/ directories, and then that discrepancy will disappear.

You won't find a .packages file served by a web server since the parent-path search is only performed on file:-locations. If the web-server is running server-side Dart and you get to place a file in its program path, you probably have bigger problems. Not to say that it's not highly exploitable, so when running a server, you might be encouraged to use the --packages command line parameter to disable the search.

**Comment by eernstg** [comment]
OK, I transferred my message and the response to
https://github.com/lrhn/dep-pkgspec, and answered there.

On Thu, May 21, 2015 at 8:42 PM, lrhn <notifications@github.com> wrote:

> We *could* try looking for packages directories in the parent path. It
> might be convenient at times.
> One of the reason for why I have chosen not to do that is as a subtle
> encouragement to switch to a .packages file.
>
> Eventually pub will stop creating packages/ directories, and then that
> discrepancy will disappear.
>
> You won't find a .packages file served by a web server since the
> parent-path search is only performed on file:-locations. If the web-server
> is running server-side Dart and you get to place a file in its program
> path, you probably have bigger problems. Not to say that it's not highly
> exploitable, so when running a server, you might be encouraged to use the
> --packages command line parameter to disable the search.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/package_config/issues/6#issuecomment-104384038>
> .
>



-- 
Erik Ernst  -  Google Danmark ApS
Skt Petri Passage 5, 2 sal, 1165 København K, Denmark
CVR no. 28866984

**Comment by lrhn** [comment]
The discovery library now does the search for .packages or packages/ according to the "DEP algorithm".
