### ISSUE TITLE
[1.9] A way to serialize/deserialize a package config to/from raw data (String or bytes)

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package_config#62]
The test_core package currently sends a .packages file to the browser for stack trace mapping purposes. It sends the same one that is used to compile with dart2js, and so it needs to be able to serialize/deserialize it.

This functionality exists but is hidden. Deserializing can be done but is cumbersome (using a loader or fake file), but serialization cannot be done today as the only exposed api just takes a directory.

This also makes testing anything that takes a package config in its api more difficult than it should be (a PackageConfig.fromJson or equivalent api would be easier to use).

See also https://github.com/dart-lang/package_config/issues/59 which is related - exposing the dart:io types causes other problems and should really be hidden behind a different library entrypoint. The main one should only deal in terms of Strings or bytes imo and be cross platform.

@lrhn

**Comment by lrhn** [comment]
There is a separation between *finding* a file and *parsing* a file.

We'd have to separate the API into different *libraries* in order to make the distinction, so one package contains only the data types and parsing, and another library contains the search logic.
That's what the original v1 version did.

It would mean that making `load` a static method on `PackageConfig` would be impossible, since `PackageConfig` could not depend on I/O operations.

We can't be all things to all people. 
This library is intended for users who need to read Dart files, so being able to read files is taken as a given. I am not sure the extra complexity of separating concepts is worth the effort if nobody will be using them separately anyway.

**Comment by jakemac53** [comment]
> This library is intended for users who need to read Dart files

I would argue this library should also be usable by libraries that want to receive a representation of a package_config.json file in their api (for mapping to/from package uris and the actual uris those represent). It should essentially be the canonical representation of this file format.

Any of those libraries should be able to write unit tests, which should not require doing file i/o (they should be able to run their tests on all the platforms they support, not all of which should be required to have file i/o available).

Following that same logic taking this dependency should not restrict the platforms on which those packages can be used, as there is at least one desired use case for this across all platforms which is stack trace mapping.

**Comment by lrhn** [comment]
The `PackageConfig` interface class now has parseX methods and toX methods for bytes, strings and JSON structures.
