### ISSUE TITLE
Add a script that can take a `.packages` file and produce a `.dart_tool/package_config.json` file.

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package_config#87]
This will allow workflows in the flutter repo to continue producing their `.packages` files, but also get a valid `.dart_tool/package_config.json` file from that.

Generally it is much easier for users to produce the `.packages` files as opposed to implementing the reading of pubspecs etc themselves.

**Comment by jakemac53** [comment]
Actually we may want this to live somewhere else... it ends up needing yaml and pub_semver deps.

**Comment by lrhn** [comment]
The existing package functionality should be able to do this.

If you use this package to read a `.packages` file into a `PackageConfig`, and then write that as a `package_config.json` file, you should get a file with the same package resolution, and a language version of 2.7 on all packages (which is the language version used when using a `.packages` file, the one prior to language versioning being released).

More precisely, something like:
```dart
import "package:package_config/package_config.json";
import "package:path/path.dart" as path;

Future<void> convertDotPackages(File dotPackagesFile) async {
   var config= await loadPackageConfig(dotPackagesFile, preferNewest: false);
   if (config.configVersion > 1) return; 
   var target = Directory(path.dirname(dotPackagesFile.path));
   // Also overwrites .packages.
   await savePackageConfig(config, targett);
}
```
If `savePackageConfig` had a way to *not* write the `.packages` file, then that would be neat, but since saving it is functionality we want to drop later, I don't want to mention it in the API.

**Comment by jakemac53** [comment]
This probably should have been closed once we implemented it in flutter, closing now :).

The idea was just to have a central place but the required deps to do the needed things here (notably, reading pubspec.yaml files for language versions) make it not a good candidate for this package.
