### ISSUE TITLE
No way to write non-relative paths.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/package_config#99]
When pub creates a .dart_tool/package_config.json file the package entries look like:
```
    {
      "name": "_fe_analyzer_shared",
      "rootUri": "file:///Users/sigurdm/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-11.0.0",
      "packageUri": "lib/",
      "languageVersion": "2.2"
    },
```

When flutter  loads that package_config and adds a package and rewrites the package_config with an extra entry (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L470), the entries end up like:
```
    {
      "name": "_fe_analyzer_shared",
      "rootUri": "../../../.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-12.0.0",
      "packageUri": "lib",
      "languageVersion": "2.2"
    },
```
Which is surprising (that you cannot round-trip without going to relative paths).

Also 'lib/' is changed to 'lib' - kind of unnecessarily.

Coming up in the context of https://github.com/flutter/flutter/issues/73870

**Comment by jakemac53** [comment]
It is worth noting that in the pub case the absolute uri is concretely better as well - the pub cache location is very unlikely to change while the package itself might be more likely to change directories. With the absolute uris the package config would continue to work, while with the relative uris it would only work if it is moved to be a sibling of the original package directory.

This is somewhat specific to pub because of the pub cache always being in a canonical location - most other use cases the relative paths would be better and that is still the best _default_ imo.
For other cases the relative paths are b

**Comment by sigurdm** [comment]
Curious.. what other cases do you have in mind?

**Comment by jakemac53** [comment]
The other use cases are primarily build related - you generally should not have absolute system paths in the outputs of any build steps so that the output is portable. So generated package configs either should use relative paths or a custom uri scheme to replace the portion of the uri that is above the output directory.

**Comment by jonasfj** [comment]
> most other use cases the relative paths would be better and that is still the best default imo.

So we have a few options:

(A) Extend the `Package` object with a option for whether the `Uri` should be serialized as relative or absolute when the user calls `savePackageConfig`, or,
(B) Extend `savePackageConfig` with an option listing the packages for which the root uri should be absolute, and extend `loadPackageConfig` to also return a list of which packages for which the root Uris were absolute.
(C) Don't make `Package.root` absolute, or at-least give the `Package` object a private option for remembering if it was serialized as absolute or relative.

I don't see any particularly pretty options here :rofl: 

I'm guessing that `Package.root` absolute is fantastic for people using `package:package_config` to read `package_config.json` files, indeed one could argue that is the common use-case. Maybe this package shouldn't offer functionality for writing `package_config.json`, since rewriting can't be done with losing information.

**Comment by jonasfj** [comment]
@lrhn thoughts? ^

In `pub` our `package_config.json` generation precedes `package:package_config` so we don't use it.
But others who load/save a `package_config.json` will render it invalid from `pub`'s perspective because we don't allow relative paths in URLs pointing into `PUB_CACHE`.

In practice, this isn't a huge issue, because we don't even allow presence of extra package names, except for the one package name that we're adding a workaround to ignore, because flutter started generating and inserting into `package_config.json`.

**Comment by sigurdm** [comment]
> invalid from pub's perspective because we don't allow relative paths in URLs pointing into PUB_CACHE.

Not so much invalid. We just recognize it is not what pub itself wrote, and therefore it must be outdated.

**Comment by sigurdm** [comment]
> (A) Extend the `Package` object with a option for whether the `Uri` should be serialized as relative or absolute when the user calls `savePackageConfig`, or,
I think we need the Package (or perhaps PackageConfig) object to know this - otherwise doing a round-trip (load a package_config.json, modify it slightly and save it back) will be very hard to do.

**Comment by lrhn** [comment]
It's possible to attach a bit to the `Package` which is only used to control whether the `packageRoot` is relativized.
It could even be set when parsing depending on whether the original was relative or not.
The `packageUriRoot` should always be relative. It must be a sub-directory of the `packageRoot`, so there won't be any leading `..`'s.
